# Generated by Django 5.1.5 on 2026-08-20 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_documents', models.IntegerField(default=0)),
                ('active_documents', models.IntegerField(default=0)),
                ('archived_documents', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('documents_uploaded_today', models.IntegerField(default=0)),
                ('document_views_today', models.IntegerField(default=0)),
                ('searches_today', models.IntegerField(default=0)),
                ('document_type_distribution', models.JSONField(default=dict)),
                ('top_uploaders', models.JSONField(default=list)),
                ('top_viewers', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, unique=True)),
                ('metric_value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['metric_name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(max_length=500)),
                ('query_type', models.CharField(choices=[('REGULAR', 'Regular Search'), ('AI', 'AI Search'), ('FILTER', 'Filter Search')], default='REGULAR', max_length=20)),
                ('results_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_view_analytics', 'Can view analytics dashboard'), ('can_export_analytics', 'Can export analytics data'), ('can_view_search_analytics', 'Can view search analytics')],
                'indexes': [models.Index(fields=['timestamp'], name='analytics_s_timesta_dab2b0_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_63c78b_idx'), models.Index(fields=['query_type', 'timestamp'], name='analytics_s_query_t_1a0d7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('DOCUMENT_VIEW', 'Document View'), ('DOCUMENT_DOWNLOAD', 'Document Download'), ('DOCUMENT_EDIT', 'Document Edit'), ('SEARCH', 'Search Performed'), ('PROFILE_UPDATE', 'Profile Update')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='analytics_u_user_id_54ee7d_idx'), models.Index(fields=['activity_type', 'timestamp'], name='analytics_u_activit_f59ac3_idx'), models.Index(fields=['timestamp'], name='analytics_u_timesta_2b8b17_idx')],
            },
        ),
    ]
